# Generated by Django 5.0.6 on 2025-05-27 22:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ctimage_dentalimage_endoscopyimage_mriimage_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='general_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ai_analysis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='endoscopyimage',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='ultrasoundimage',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='dentalimage',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='mriimage',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='ctimage',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='xrayimage',
            name='patient',
        ),
        migrations.AlterField(
            model_name='ctimage',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='dentalimage',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='endoscopyimage',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='mriimage',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='ultrasoundimage',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_image_to),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_image_to),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
