# Generated by Django 5.0.6 on 2025-05-27 22:56

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_generalimage_remove_endoscopyimage_patient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='generalimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='generalimage',
            name='body_part',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalimage',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text="AI model's confidence score (0-100)", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='generalimage',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generalimage',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generalimage',
            name='veterinarian_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generalimage',
            name='ai_analysis',
            field=models.TextField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generalimage',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_image_to),
        ),
    ]
