# Generated by Django 5.0.6 on 2025-05-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_generalimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctimage',
            name='body_part',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dentalimage',
            name='body_part',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='endoscopyimage',
            name='body_part',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='generalimage',
            name='body_part',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mriimage',
            name='body_part',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ultrasoundimage',
            name='body_part',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='xrayimage',
            name='body_part',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
